<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>PAS.ActuarialEngine</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="PAS.AspNetCore" />
    <Using Include="PAS.Core" />
    <Using Include="PAS.Persistence.Linq" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Assets\Contracts\PAS.Assets.Contracts.csproj" />
    <ProjectReference Include="..\..\Common\AspireServiceDefaults\PAS.AspireServiceDefaults.csproj" />
    <ProjectReference Include="..\..\Common\AspNetCore\PAS.AspNetCore.csproj" />
    <ProjectReference Include="..\..\Common\Core\PAS.Core.csproj" />
    <ProjectReference Include="..\..\Common\Domain\PAS.Domain.csproj" />
    <ProjectReference Include="..\..\Common\Persistence\PAS.Persistence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Domain\" />
  </ItemGroup>

</Project>
